# fly.toml app configuration file generated for jhnotes on 2023-07-07T15:28:38+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jhnotes"
primary_region = "lhr"

[env]
  PORT = "8080" # add this

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080 
  processes = ["app"]
